export {
  emailDocumentBlockSchema,
  emailDocumentSchema,
  emailMergeFieldNameSchema,
  emailPreviewRecipientSchema,
  emailTemplateAudienceSchema,
  emailTemplateCommandResponseSchema,
  emailTemplateCommandSchema,
  emailTemplateDraftSchema,
  emailTemplateIssueSchema,
  emailTemplatePreviewRequestSchema,
  emailTemplatePreviewResponseSchema,
  emailTemplatePreviewSourceSchema,
  emailTemplateRecordSchema,
  emailTemplateSchema,
  emailTemplateStatusSchema,
  emailTemplateWorkspaceSchema,
  renderedEmailTemplateSchema,
  resolvedEmailMergeFieldSchema,
  type EmailPreviewRecipient,
  type EmailTemplateCommand,
  type EmailTemplateCommandResponse,
  type EmailTemplatePreviewRequest,
  type EmailTemplatePreviewResponse,
  type EmailTemplatePreviewSource,
  type EmailTemplateRecord,
  type EmailTemplateWorkspace,
} from "./contracts.js";
export {
  campaignAudienceFilterSchema,
  campaignConfirmRequestSchema,
  campaignConfirmResponseSchema,
  campaignDeliveryCountsSchema,
  campaignDeliveryLogSchema,
  campaignDeliveryMessageSchema,
  campaignDeliveryStatusSchema,
  campaignExclusionReasonSchema,
  campaignPlanSchema,
  campaignPortalStateSchema,
  campaignPreviewRequestSchema,
  campaignPreviewResponseSchema,
  campaignReadinessSchema,
  campaignReplayRequestSchema,
  campaignReplayResponseSchema,
  campaignScheduleSchema,
  campaignSummarySchema,
  campaignWorkspaceSchema,
  type CampaignConfirmRequest,
  type CampaignConfirmResponse,
  type CampaignDeliveryCounts,
  type CampaignDeliveryLog,
  type CampaignDeliveryMessage,
  type CampaignPreviewRequest,
  type CampaignPreviewResponse,
  type CampaignReplayRequest,
  type CampaignReplayResponse,
  type CampaignSummary,
  type CampaignWorkspace,
} from "./campaign-contracts.js";
export {
  createDeterministicEmailPreviewValues,
  resolvedEmailMergeFields,
  type DeterministicEmailPreviewOptions,
} from "./preview.js";
export {
  CampaignPlanError,
  createCampaignMessageKey,
  createCampaignPlan,
  serializeCampaignPlan,
  type CampaignAudienceCandidate,
  type CampaignAudienceExclusion,
  type CampaignAudienceFilter,
  type CampaignAudienceRole,
  type CampaignAudienceSample,
  type CampaignAudienceSnapshot,
  type CampaignExclusionReason,
  type CampaignPlan,
  type CampaignPortalState,
  type CampaignReadiness,
  type CampaignSchedule,
  type CampaignSuppressionReason,
} from "./campaign.js";
export {
  emailTemplateFamilyId,
  emailTemplateHead,
  emailTemplateIdentityIssue,
  emailTemplateVersionId,
} from "./identity.js";
export {
  analyzeEmailTemplate,
  EmailTemplateValidationError,
  validateEmailMergeValues,
} from "./merge.js";
export {
  renderEmailTemplate,
  renderSanitizedEmailTemplateBody,
  type SanitizedEmailTemplateBody,
} from "./render.js";
export {
  createSeedEmailTemplates,
  type SeedEmailTemplateOptions,
} from "./seeds.js";
export {
  EMAIL_MERGE_SCHEMA_VERSION,
  emailMergeFieldDefinitions,
  type EmailAddress,
  type EmailDocument,
  type EmailDocumentBlock,
  type EmailMergeFieldName,
  type EmailMergeFieldType,
  type EmailMergeValue,
  type EmailMergeValues,
  type EmailMessage,
  type EmailSender,
  type EmailTemplate,
  type EmailTemplateAnalysis,
  type EmailTemplateAudience,
  type EmailTemplateDraft,
  type EmailTemplateIssue,
  type EmailTemplateStatus,
  type RenderedEmailTemplate,
  type ResolvedEmailMergeField,
} from "./types.js";
export {
  activateEmailTemplate,
  archiveEmailTemplate,
  createEmailTemplateRevision,
  emailTemplateDraft,
  serializeEmailTemplateSnapshot,
  snapshotEmailTemplate,
  type EmailTemplateRevisionChanges,
} from "./versioning.js";
